### ISSUE TITLE
Does this support Chinese?

### ISSUE THREAD

**Issue by MonolithFoundation** [VITA-MLLM/Freeze-Omni#11]

**Comment by wangxiongts** [comment]
Of course, our demo supports both Chinese and English input and output.

**Comment by MonolithFoundation** [comment]
Does it support speech style transfer? or voice cloning?

**Comment by wangxiongts** [comment]
Freeze-Omni currently does not support a zero-shot TTS capability. As far as I know, few duplex dialogue models support this capability now. However, Freeze-Omni retains text output, so you can support this capability by connecting a TTS model with style transfer or voice cloning.
