### ISSUE TITLE
Are you planning to release the source code?

### ISSUE THREAD

**Issue by pashanitw** [VITA-MLLM/Freeze-Omni#2]
This is a really clever technique, especially the speech decoder part. Are you planning to release the training? I'd love to learn more about it.

**Comment by wangxiongts** [comment]
Hi, thanks for your attention to our work. We have submitted the open-source code, yet it is being reviewed internally. We are moving the process forward as quickly as possible, stay tuned :)

**Comment by wwfcnu** [comment]
代码审核时间好长呀

**Comment by wangxiongts** [comment]
内部需要走2~4周的流程，我们已经在尽快加速了，抱歉久等啦

**Comment by WendongGan** [comment]
你好， 请问训练相关的代码会开源么？

**Comment by wangxiongts** [comment]
> 你好， 请问训练相关的代码会开源么？

由于训练代码涉及到一些内部业务逻辑，我们还在争取开源训练代码的可能性，目前开源出来的code中已经尽可能的保留了一些模型forward的内容先供参考
