### ISSUE TITLE
duplex state token learning

### ISSUE THREAD

**Issue by xxchauncey** [VITA-MLLM/Freeze-Omni#4]
你好，

请问state token 1和2，即LLM判定用户结束输入以及LLM判定为无关query的训练数据是如何构造的？是否有LLM对打断判定的准确率的相关指标？

**Comment by xxchauncey** [comment]
感谢回复，确实构造的无关query会和实际场景有一些偏差，像拒识任务实际测试时难免会有不少bad case。

**Comment by xxchauncey** [comment]
抱歉还有一个问题需要请教您：

在speech decoder部分，NAR和AR Decoder具体是怎么运作的？paper中指出是参考VALL-E的做法，在VALL-E中，AR decoder用于预测第一个codebook，NAR用于预测剩余的codebook。在Freeze-Omni中，codebook应该是只有单个的。

**Comment by wangxiongts** [comment]
> 抱歉还有一个问题需要请教您：
> 
> 在speech decoder部分，NAR和AR Decoder具体是怎么运作的？paper中指出是参考VALL-E的做法，在VALL-E中，AR decoder用于预测第一个codebook，NAR用于预测剩余的codebook。在Freeze-Omni中，codebook应该是只有单个的。

这个是这样的，我们主要是参考了VALL-E这种从semantic表征通过AR结构产生code的范式，而在Freeze-Omni中，具体的NAR和AR Decoder实际上是共享参数，类似于LLM中prefill和generate的过程，NAR Decoder对semantic表征进行建模得到kv-cache，然后以这个kv-cache为基础进行step by step的AR decode

**Comment by xxchauncey** [comment]
明白了，所以在训练的时候，speech code token之前的sequence是NAR来提取的，后面的speech code token是由AR来逐步生成的。

既然他们共享权重，那应该是通过控制attn mask的方法来改变NAR和AR的对吗？
