### ISSUE TITLE
交互模式没有反应

### ISSUE THREAD

**Issue by fromlimbo** [VITA-MLLM/Freeze-Omni#5]
感谢开源，刚刚在本地把服务起来后，点击页面start后没有任何反应，麦克风是正常的，但是就是没有声波进去
![image](https://github.com/user-attachments/assets/8bbb32e0-1b2b-4bd0-a566-e8d7f142587c)

**Comment by wangxiongts** [comment]
您好，可以检查下这一块

**Comment by wangxiongts** [comment]
感谢对工作的支持，可以从下面几个方面check下
1：浏览器的麦克风权限是否打开，建议使用chrome
2：F12看下前端页面是否在控制台有输出报错
3：检查下后端是否有SID连接的信息
正常情况下，如果demo运行起来了，Input Waveform会有声波显示，后端也会输出receive PCM的信息

**Comment by fromlimbo** [comment]
> 感谢对工作的支持，可以从下面几个方面check下 1：浏览器的麦克风权限是否打开，建议使用chrome 2：F12看下前端页面是否在控制台有输出报错 3：检查下后端是否有SID连接的信息 正常情况下，如果demo运行起来了，Input Waveform会有声波显示，后端也会输出receive PCM的信息

感谢，chrome有效
