### ISSUE TITLE
能否开源训练代码呢？

### ISSUE THREAD

**Issue by EdisonZhu33** [VITA-MLLM/Freeze-Omni#6]
能否开源训练代码呢？

**Comment by wangxiongts** [comment]
由于训练代码涉及到一些内部业务逻辑，我们还在争取开源训练代码的可能性，目前开源出来的code中已经尽可能的保留了一些模型forward的内容先供参考，如果有任何训练细节相关的问题，可以先加微信群讨论

**Comment by fromlimbo** [comment]
可以留一个微信群吗？
