### ISSUE TITLE
测试推理过程中有inf, nan的bug

### ISSUE THREAD

**Issue by fromlimbo** [VITA-MLLM/Freeze-Omni#7]
试用过程中多对话几次就会出现如下bug：
    token_index = torch.multinomial(probs, 1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by fromlimbo** [comment]
> 具体使用的是什么样的机器环境呢？因为我们的模型是在bfloat16的情况下训练的，所以如果是float16的环境下推理，可能会出现数组问题

A800 和 4090 都有类似的问题，环境是按照你们 readme 创建的，没有更改过代码。我觉得 probs 应该要做一下检查，这里确实容易出现 nan 或者除 0 问题

**Comment by wangxiongts** [comment]
可以在推理的时候打印下models/decoder/decoder.py里infer函数的top k sampling部分中softmax后的probs看下，我们之前在内部验证的时候，H20的机器上会出现一些类似的问题，后来是通过升级cublas的版本来恢复正常的。
