### ISSUE TITLE
群友正在尝试复现这个论文，建了一个语音AI微信群（40个人左右）有兴趣的一起讨论。 Chat Group to discuss the implementation of this paper

### ISSUE THREAD

**Issue by tianke0711** [VITA-MLLM/Freeze-Omni#9]
群友正在尝试复现这些端到端的论文（freeze-omni, llama-omni），建了一个语音AI微信群（40个人左右）有兴趣的一起讨论。
 Chat Group to discuss the implementation of this paper。
主要是各个大学的硕博研究生以及企业研发人员。非诚勿扰！谢谢。
如果有兴趣，请发邮件(请简单自我介绍)： sciscipaper@gmail.com

**Comment by MonolithFoundation** [comment]
![51733367187_ pic](https://github.com/user-attachments/assets/a979922b-a260-4134-acf0-1e13d750edbe)

**Comment by zzhdbw** [comment]
> ![51733367187_ pic](https://github.com/user-attachments/assets/a979922b-a260-4134-acf0-1e13d750edbe)

请求更新二维码
